#!/usr/bin/env bash

if ! command -v docker &> /dev/null; then
  echo "Docker not installed, skipping..."
  exit 1
fi

if [ "$(docker images -q stklos)" != "" ]; then
  docker run --platform linux/amd64 -ti -v $(pwd):/home stklos 
else
  docker build --platform linux/amd64 -t stklos .
fi
