#!/usr/bin/env bash

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
  echo "Docker not installed, skipping..."
  exit 1
fi

docker-compose up -d
docker exec -it stklos-dev stklos
